<?= $this->extend($layout ?? 'layouts/main_user') ?>
<?= $this->section('content') ?>

<div class="container-fluid">
    <?php if (session()->getFlashdata('error')): ?><div class="alert alert-danger border-0 shadow-sm"><?= esc(session()->getFlashdata('error')) ?></div><?php endif; ?>

    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
        <div>
            <h3 class="mb-1">Email Preview</h3>
            <p class="text-muted mb-0">This is the email content generated by the system.</p>
        </div>
        <div class="d-flex gap-2">
            <a href="/dashboard/emails" class="btn btn-outline-secondary">Back to Inbox</a>
            <a href="/dashboard/notifications" class="btn btn-outline-primary">Notifications</a>
        </div>
    </div>

    <div class="card border-0 shadow-sm mb-4">
        <div class="card-body">
            <div class="d-flex flex-column flex-md-row justify-content-between gap-3">
                <div>
                    <div class="text-muted small">Subject</div>
                    <div class="fw-semibold"><?= esc($email['subject'] ?? 'Email') ?></div>
                </div>
                <div>
                    <div class="text-muted small">To</div>
                    <div class="fw-semibold"><?= esc($email['to_email'] ?? '-') ?></div>
                </div>
                <div>
                    <div class="text-muted small">Generated</div>
                    <div class="fw-semibold"><?= esc(! empty($email['created_at']) ? date('d M Y H:i', strtotime($email['created_at'])) : '-') ?></div>
                </div>
            </div>
            <?php if (! empty($email['has_attachment'])): ?>
                <div class="mt-3">
                    <span class="badge rounded-pill bg-light text-dark border">Attachment</span>
                    <span class="small text-muted ms-2"><?= esc($email['attachment_name'] ?? 'calendar.ics') ?></span>
                </div>
            <?php endif; ?>
        </div>
    </div>

    <div class="card border-0 shadow-sm">
        <div class="card-body">
            <div class="email-preview">
                <?= $email['body'] ?? '' ?>
            </div>
        </div>
    </div>
</div>

<?= $this->endSection() ?>
